### ISSUE TITLE
Validate syntax in CSS

### ISSUE THREAD

**Issue by h3xar0n** [dpsnesbitt/Projects-Dasmoto#4]
In CSS there are a few tiny things we need to fix:

Replace the colon with a comma to avoid fonts from being misread: 

https://github.com/dpsnesbitt/Projects-Dasmoto/blob/4af6f41707444d191796f9af215eb9c33d9300a6/style.css#L4

```css
  font-family: Helvetica, cursive;
```

Add a colon after `font-size: 32px` to indicate a line break:

https://github.com/dpsnesbitt/Projects-Dasmoto/blob/4af6f41707444d191796f9af215eb9c33d9300a6/style.css#L24-L25

```css
.item h2 {
  color: white;
  font-size: 32px;
  font-weight: bold;
}
```
